### ISSUE TITLE
Add model calibration workflow

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#245]
Direct access to Optuna via `sim.calibrate` has proven to be a useful workflow. I gather than trainees will not be performing model calibration, but we may need calibration as part of building baseline modules. Probably not a highest priority issue and unsure if needed for APHRC, but likely easy to port over from other Starsim models.

**Comment by cliffckerr** [comment]
We've been getting questions on calibration so frontlogging this!!

**Comment by cliffckerr** [comment]
Closed by #581
