### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by robynstuart** [starsimhub/starsim#248]
- [ ] disease
- [ ] diseases.examples
- [ ] diseases.gonorrhea
- [ ] diseases.hiv
- [ ] diseases.syphilis
- [ ] distributions
- [ ] interventions
- [ ] modules
- [ ] networks
- [ ] parameters
- [ ] people
- [ ] products
- [ ] random
- [ ] results
- [ ] settings
- [ ] sim
- [ ] states
- [ ] utils

**Comment by cliffckerr** [comment]
Most, but not all, seem to be in place

**Comment by cliffckerr** [comment]
Going to close for now -- we can add more as needed.
