### ISSUE TITLE
Developer guide tutorials

### ISSUE THREAD

**Issue by robynstuart** [starsimhub/starsim#251]
- [x] D1 - Defining diseases
- [x] D2 - Defining networks
- [x] D3 - Defining interventions and analyzers
- [ ] D4 - Understanding demographics
- [ ] D5 - Understanding distributions

**Comment by kaa2102** [comment]
https://pypi.org/project/starsim/
https://docs.idmod.org/projects/starsim/en/latest/

**Comment by robynstuart** [comment]
- D1 - Defining diseases - _already in the main tutorials_
- D2 - Defining networks - _already in the main tutorials_
- D3 - Defining interventions and analyzers _interventions in the main tutorials_, analyzers add on #584 
- D4 - Understanding demographics - don't think we need this??
- D5 - Understanding distributions - added a tutorial on #584 for defining parameter values. For details on CRN we should probably refer people to the paper.

**Comment by cliffckerr** [comment]
Closed by #584
