### ISSUE TITLE
Distribution validation

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#293]
Users shouldn't be able to substitute a Gaussian in place of a Bernoulli, etc. Need sufficient compatibility checking.

**Comment by robynstuart** [comment]
I guess they could use the delta distribution (if we end up going with that). But that's likely a weird corner case

**Comment by cliffckerr** [comment]
Fixed, `filter` is now only available for Bernoulli distributions. Otherwise, the user _could_ mess them up, but I don't think this is more of a risk than other things, and you get a reasonably clear error mesage:
```
import starsim as ss

pars = dict(
    diseases = dict(
        type = 'sir',
        p_death = ss.lognorm_ex(),
    ),
    networks = 'random'
)

sim = ss.Sim(pars)
sim.run()
sim.disp()

IndexError: arrays used as indices must be of integer (or boolean) type
```
