### ISSUE TITLE
Cholera ti_symptomatic

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#306]
Code was:
```
# Determine when exposed become infected
self.ti_infected[uids] = sim.ti + p.dur_exp2inf.rvs(uids)

# Determine who becomes symptomatic and when
symp_uids = p.p_symp.filter(uids)
self.ti_symptomatic[symp_uids] = sim.ti + p.dur_exp2inf.rvs(symp_uids)
```

Which calls the `dur_exp2inf` distribution twice in one step, and is therefore not RNG safe (and will now throw an error if multirng is enabled).

If `ti_symptomatic` should be a separate draw, it needs a separate distribution. For now, I'm just going to set `self.ti_symptomatic[symp_uids] = self.ti_infected[symp_uids]`

**Comment by cliffckerr** [comment]
Should be fixed now
