### ISSUE TITLE
Refactor to only call random streams once per step

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#312]
There are (at least) two places in the code where the same random number distribution is called more than one time on a single timestep. Doing so is not common random number safe, and the code now raises an exception.

As a temporary workaround, I have reset the random state, e.g.
```python
self.random_state.step(self.sim.ti+1) 
```
The above code does NOT step the random state forward in time despite the `ti+1` argument. This is simply resetting the random state to how it would have been at the beginning of THIS timestep.

However, this hack is not efficient and potentially not scientifically safe. The underlying code should be refactored, or we need to create separate random number generators for each call.

The two place where this hack is in place are:
1. distribution.py near line 140
2. products.py near line 118

**Comment by cliffckerr** [comment]
Closed by #645
