### ISSUE TITLE
Track GitHub Traffic

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#361]
GitHub tracks "Traffic" (under Settings) for the past two weeks. We need a cron job that downloads that data so we can track trends over time.

**Comment by kaa2102** [comment]
I will set up a cron job from a Google Cloud vm instance or a Jupyter Notebook Scheduler (less reliable, will work when I am logged on) and send a daily update to Slack #documents via the Slack API.

This code was shared in Microsoft Teams to pull daily unique traffic data from our GitHub repo.
`#Python
import requests

#starsim statistics OR insights GitHub API link
url = "https://api.github.com/repos/amath-idm/starsim/traffic/clones" 
#url="https://api.github.com/repos/starsimhub/starsim/traffic/clones"# new url
headers = {
    "Authorization": "<Your Access Token>", # Must have Admin Rights to Access
    "Accept": "application/vnd.github.v3+json"
}

response = requests.get(url, headers=headers)
traffic_data=response.json()

print(traffic_data["count"])
print(traffic_data["unique"])

#Create List to Store Data
series_data=[]

#Append Traffic Data to List
for data in traffic_data["clones"]:
    date_element=data["timestamp"]
    clone_count=data["count"]
    unique_count=data["unique"]
    series_data.append([data_element,clone_count,unique_count])
  
 print(series_data)`

**Comment by kaa2102** [comment]
A GitHub workflow leveraging the ['github-repo-stats](https://github.com/jgehrcke/github-repo-stats#terminology-stats-repository-and-data-repository)' Action were set up on Friday, March 8th. The Action was successfully triggered manually on 3/8/2024 and triggered automatically on 3/9 and 3/10 at 2300 UTC.

The Action created a data branch called 'github-repo-stats' that 100% mirrored the main branch file structure AND created a 'starsimhub/starsim' folder on the main branch. The  'github-repo-stats'  branch was emptied to only retain the data collection folder and the 'starsimhub/starsim' folder was deleted from the main branch. The manual 'github-repo-stats' Action was triggered to test that the process still works with the updates. This Issue can be closed.
