### ISSUE TITLE
Write intro for docs page

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#368]
A giant table of contents is not *the* most user friendly landing page:
![image](https://github.com/starsimhub/starsim/assets/3239256/1cc5005c-32f9-4abc-983b-580e0a14abb1)

https://starsim.readthedocs.io/en/latest/

**Comment by kaa2102** [comment]
I am leveraging the Covasim description in GitHub and PyPi to create a draft for a Starsim intro & description. 

[PyPi Covasim Project Description.docx](https://github.com/starsimhub/starsim/files/14538485/PyPi.Covasim.Project.Description.docx)

**Comment by menriquez-IDM** [comment]
Keith, do you want to assign it to yourself? :)  I had already started working on it (ja ja)

**Comment by kaa2102** [comment]
Perhaps we can work on it together <tag team>. I leveraged the PyPi description and Covasim to draft documents we can use later. This is also in the Slack #documents channel.
[DRAFT Starsim Description.docx](https://github.com/starsimhub/starsim/files/14543758/DRAFT.Starsim.Description.docx)

**Comment by cliffckerr** [comment]
Going to close for now since we have content, but can continue building this out
