### ISSUE TITLE
Update URLs to reflect starsimhub org 

### ISSUE THREAD

**Issue by menriquez-IDM** [starsimhub/starsim#376]
# Update URLS 
Scan files for URLs pointing to amath-idm and update them to point to the new Organization (if appropriate). Sometimes we add an url to an issue and/or branch in the docstrings or comments as reference.   I think this could be done before or after the code base has been migrated.

- redirect from instititutefordiseasemodeling -> starsimhub

- scope: code comments, documentation

**Comment by cliffckerr** [comment]
I think this should be fine to close -- I didn't see any references to either URL.

**Comment by menriquez-IDM** [comment]
Fixed. Thanks Cliff!
