### ISSUE TITLE
The footer.html customization isn't being applied in the Sphinx PyData theme

### ISSUE THREAD

**Issue by JSchripsema-IDM** [starsimhub/starsim#381]
There's extra information about the license, privacy notice, and terms of use that isn't being applied to the compiled HTML in the PyData theme. It appears others have hit this issue and identified a fix here: https://github.com/pydata/pydata-sphinx-theme/issues/1284

**Comment by cliffckerr** [comment]
Good news and bad news -- I fixed it, but it looks awful! Much as I love div-wrangling, I could use help from an HTML person here!
![image](https://github.com/starsimhub/starsim/assets/3239256/8fa9b20c-72b8-46e9-9309-af6ed5692f92)

**Comment by cliffckerr** [comment]
Fixed -- not beautiful, but not embarrassing :)
![image](https://github.com/starsimhub/starsim/assets/3239256/138ba442-d186-4d0f-aae1-16011ce3d1f6)
