### ISSUE TITLE
Custom demographics not working

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#384]
`Pregnancy` and `Deaths` classes have a user-configurable Bernoulli distribution parameters that should be able to control the probability of pregnancy/death for each agent on each step. But it looks from the code like this functionality is not working. 

In `Deaths`, `make_death_prob_fn` overwrites `self.pars.death_rate` without consideration of custom user-supplied distributions.

`Births` should take a parallel approach.

**Comment by kaa2102** [comment]
Custom parameter provided as input `self.pars.death_rate` is not overwritten by default parameters:

**Testing File**
```
demographics = [
    ss.Births(pars={'birth_rate': 27}),
    ss.Deaths(pars={'death_rate': 50}) # 50 per 1000 death rate = 0.05
    ]
```
**_demographics.py_**
```
        self.default_pars(
            rel_death = 1,
            **death_rate = 20,  # Default = a fixed rate of 2%/year, overwritten if data provided**
            units = 1e-3,  # assumes death rates are per 1000. If using percentages, switch this to 1
        )

```

**Output**

```
Death Prob = 0.05 # print("Death Prob = "+str(death_prob)) from demographics.py
52.39631041224955 # print(np.average(sim.results['deaths']['cmr'])) in testing file
2.607497152300453 # print(np.std(sim.results['deaths']['cmr'])) in testing file

```
