### ISSUE TITLE
Empty networks evaluate as `False`

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#393]
Got tripped up by this recently:
```py
import starsim as ss
m = ss.Module()
n = ss.Network()

print(bool(m))
print(bool(n))

True
False
```
It's because networks have a defined `__len__`, which evaluates to 0, which then returns `False`. I guess this is ok? But it's a bit of a gotcha (it got me!). (Solution is to be sure to use `if net is not None` rather than `if net`, of course.)

**Comment by pausz** [comment]
Definitely something to document :). 

Debate topic:  I think length of a network can be a bit ambiguous. It could be the number of nodes or the number of edges, right?  I was expecting number of nodes when I first played around with networks.

**Comment by cliffckerr** [comment]
True, I think we went with edges since (a) a node with no edges has no effect, (b) many of our networks have all agents as nodes

**Comment by cliffckerr** [comment]
Going to close this since an edgeless network kind of _is_ "falsey".
