### ISSUE TITLE
Many disease modules are neglecting dt

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#402]
Often see 
```python
ti_event = sim.ti + draw_from_duration_distribution
```
But this is mixing time time (ti) with time (the distribution draw).

**Comment by daniel-klein** [comment]
Noticed yesterday that the measles model has parameters in days (according to the comment), but they are used as years. Addressed in #411, but that is a draft PR.

**Comment by cliffckerr** [comment]
Merged
