### ISSUE TITLE
Revisit hash & cache

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#406]
Revisiting the hash & cache idea: #243

Further investigation shows that it's 3x faster even for the same number of random numbers. But we don't usually need n_agents(*slot_scale) random numbers; we usually need many fewer than that. So we should actually be able to get a 30x speed increase this way. This should dwarf the 3x penalty of using `scipy.stats.<dist>.ppf` in cases where we need complex distributions.

**Comment by daniel-klein** [comment]
Just added some comments on #243, including a link to key-based random number generation for exploration:

Widynski, Bernard. “Squares: A Fast Counter-Based RNG.” arXiv, March 13, 2022. https://doi.org/10.48550/arXiv.2004.06278.

**Comment by cliffckerr** [comment]
Going to re-close -- it's fast enough for now. The absolute simplest (and wrong) version:
```
# Original
rvs_s = self.rng_source.rvs(src)
rvs_t = self.rng_target.rvs(trg)
rvs = rvs_s + rvs_t

# Minimal
rvs_s = self.rng_source.rvs(src)
rvs = rvs_s*2 # wrong!
```
is only about 20% faster.
