### ISSUE TITLE
Refactor RNG revisions

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#408]
- [x] Reimplement slots using ppf
- [x] Add more realistic performance test
- [x] Do benchmarking
- [x] Add minimum-possible-worlds-change test
- [x] Combine `rvs` and `urvs`
- [x] Think about how to implement strictness in a safe but convenient way
- [x] Think about how to handle lognormal distribution defaults
- [x] Rename dists to distributions
- [x] Fix docstring saying "unique" name in dists.py
- [x] Update docstring for initialize, and rename module and sim _module and _sim
- [x] Remove unneeded .initialize() from tests

**Comment by daniel-klein** [comment]
@cliffckerr, could you please explain the first point, "Reimplement slots using ppf"?

**Comment by cliffckerr** [comment]
Working out final details, hope to explain by way of a PR this evening :)

**Comment by cliffckerr** [comment]
Moved outstanding issues to #426
