### ISSUE TITLE
Refactor RNG PPF revisions

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#422]
Issues arising from #420 :
- [x] Convert `ss.random()` etc. into subclasses of `ss.Dist` rather than functions
- [x] Move `filter` to `ss.bernoulli()` subclass
- [ ] Make `ss.choice` CRN-safe (in general and in `syphilis.py`)
- [ ] Write CRN-safe `randround`
- [x] Handle missing slots more elegantly
- [ ] Change defaults to `strict=True, auto=True` which auto-increments the RNG after use
- [x] Tidy/check `has_array_pars` logic
- [ ] Handle the many `TODO` comments
- [ ] Check that `test_syphilis.py` is doing the right thing on this branch
- [ ] Check performance (see below)

See also https://github.com/starsimhub/starsim/issues/408

For performance, currently this branch is much slower on `benchmark_full.py`, although this might have to do with that particular test, since other things don't seem to be slower (e.g. the test suite takes about 4.5 s on both this branch and `main`):
```
python benchmark_full.py 
Starsim 0.3.0 (2024-03-18) — © 2023-2024 by IDM
—————————————————————
Average: 5296 ± 39 ms
—————————————————————


Switched to branch 'main'

python benchmark_full.py 
Starsim 0.2.10 (2024-03-18) — © 2023-2024 by IDM
——————————————————————
Average: 3363 ± 221 ms
——————————————————————
```

**Comment by cliffckerr** [comment]
Another benchmarking test, `benchmark_sir.py`, that illustrates the performance difference starkly (this branch 2x slower than main):
```py
#!/usr/bin/env python3
"""
Larger test of sim performance.
"""

import sciris as sc
import starsim as ss

# Define the parameters
repeats = 3
pars = sc.objdict(
    n_agents = 100_000,
    n_years  = 100,        # Number of years to simulate
    dt       = 0.5,        # Timestep
    verbose  = 0,          # Don't print details of the run
    diseases = 'sir',
    networks = 'random',
)

def make_run_sim():
    """ Make and run a decent-sized default simulation """
    sim = ss.Sim(pars=pars)
    sim.run()
    return sim


if __name__ == '__main__':
    
    T = sc.timer()
    for r in range(repeats):
        make_run_sim()
        T.tt(f'Trial {r+1}/{repeats}')
        
    sc.heading(f'Average: {T.mean()*1000:0.0f} ± {T.std()/len(T)**0.5*1000:0.0f} ms')
```

**Comment by cliffckerr** [comment]
Setting `slot_scale = 2` reduces this from 20.7 s to 18.3 s, so some improvement, but not much. Need to investigate further.

**Comment by daniel-klein** [comment]
The default "sir" on "random" does not have any transmission ongoing for a majority of that 100 year period, consider adjusting disease or network parameters for a more representative test case, or just shorten the time period.
<img width="752" alt="image" src="https://github.com/starsimhub/starsim/assets/15837372/d2ff19e8-7df5-4b88-8fc4-c3d2cfc51443">

**Comment by daniel-klein** [comment]
The plot above comes from `sim.diseases['sir'].plot()`, which places `ti` on the x-axis. This means that transmission is only active for the first 12 years considering `dt=0.5`.

**Comment by cliffckerr** [comment]
I got another almost 2x speed improvement by doing the 'remainder' step on the slots, rather than on the rvs themselves ... kind of a hash & cache approach :)

**Comment by daniel-klein** [comment]
Remainder might be overkill. We're adding two numbers, each [0,1). The result has to be in the range of [0,2).

If the sum > 1, subtract 1.
```python
rvs = rvs_s + rvs_t
inds = np.where(rvs>1)[0]
rvs[inds] -= 1
```

Might be faster?

**Comment by daniel-klein** [comment]
Running for 15 years instead of 100 should give very similar results because there is little transmission happening after year 15.

**Comment by cliffckerr** [comment]
Moved oustanding issues to #426
