### ISSUE TITLE
Add ODD protocol to docs

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#433]
https://jasss.soc.surrey.ac.uk/23/2/7.html

**Comment by kaa2102** [comment]
Reviewed the article and I will incorporate ODD best practices into user documentation where applicable. https://jasss.soc.surrey.ac.uk/23/2/7.html

**Comment by devclinton** [comment]
@kaa2102 - confused with this status. Is this in progress, todo, or done at moment?

**Comment by kaa2102** [comment]
Update: The ODD Starsim docs are In Progress. I am using feedback from papers sent by @cliffckerr and @pausz to create a draft Starsim ODD paper. I will have a preliminary draft ready next week.
