### ISSUE TITLE
Consider network.contacts → network.edges

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#437]
I think of contacts as something a person (not a population) has, so `n_contacts` should be the number of contacts (on average) per person. But then for consistency, maybe we should rename `network.contacts` to `network.edges`, since that more accurately captures what they are (and since it's more natural to think of edges as a network, not a node/agent, property).

**Comment by kaa2102** [comment]
I agree that network.edges is a more accurate description.

**Comment by daniel-klein** [comment]
edges or even edgelist, let's make the change. "edges" is fine.

**Comment by cliffckerr** [comment]
Change coming in #503!

**Comment by cliffckerr** [comment]
(Actually I'll split this out into a separate PR.)

**Comment by cliffckerr** [comment]
Closed by #527
