### ISSUE TITLE
Rethink auto-jump in Dist

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#438]
Wait, just seeing the `auto` advance in `Dist`, which seems to circumvent `strict` as it defaults to True. Auto advancing is safe in some cases, but not others. There are really just a handful of places where `auto` is needed, like in the new pairwise transmission code. Recommend investigating permanent solutions for these challenge spots rather than auto jumping.

_Originally posted by @daniel-klein in https://github.com/starsimhub/starsim/issues/428#issuecomment-2032590552_

**Comment by daniel-klein** [comment]
Thanks @cliffckerr. Auto jumping is not CRN safe in certain situations, I would like to avoid it if at all possible.

**Comment by cliffckerr** [comment]
Duplicate of #312
