### ISSUE TITLE
Fix SIR plotting

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#440]
Uses timestep rather than sim step -- would be fixed if modules had access to the Sim object.

**Comment by daniel-klein** [comment]
As far as I know, SIR is unique in having a `plot()` method as part of the disease module. Seems like a reasonable pattern, but does not extend well to multi-disease simulations etc. In addition to`module.plot()`, we previously discussed a pattern like `sim.plot(modules=sir)`.

**Comment by cliffckerr** [comment]
Closed by #488
