### ISSUE TITLE
Add plot() to MultiSim()

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#442]
By default, `multisim.plot()` should be the same as `sim.plot()`, except with uncertainty bounds.

**Comment by daniel-klein** [comment]
Just noting that previous starsim models have included the ability to `plot()` a `MultiSim` object, and it was quite helpful. Could be somewhat different here in the Starsim Framework considering the modular structure, but we have a possible starting point.

**Comment by cliffckerr** [comment]
Closed by #581
