### ISSUE TITLE
Allow age_data values to handle ints

### ISSUE THREAD

**Issue by skroiss-idm** [starsimhub/starsim#447]
An error is thrown if the 'values' column in age_data are of datatype int64.

**Comment by kaa2102** [comment]
Are we considering (1) changing the data type or (2) going upstream to enable the class parameters to accept int64?

**Comment by daniel-klein** [comment]
Perhaps related to #451?

**Comment by devclinton** [comment]
@skroiss-idm  - Is this fixed with #451?

**Comment by skroiss-idm** [comment]
Ahh, yes. Looks like that's fixed! Thanks for flagging.
