### ISSUE TITLE
make_new_cases is too complex

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#475]
People who want to modify beta (e.g., to add seasonality) have to go through a byzantine process of copy-pasting and editing `make_new_cases`, which is one of the most complex parts of the code. Figure out how to make this more straightforward.

**Comment by daniel-klein** [comment]
Agree, although wouldn't it be possible to subclass and just add one line to modify beta before calling the parent? Anyway, seasonality should be a "framework feature" that doesn't have to be reinvented for each application.

**Comment by cliffckerr** [comment]
Closing in favor of #439
