### ISSUE TITLE
Forking error

### ISSUE THREAD

**Issue by CYGUBICKO** [starsimhub/starsim#476]
Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.

**Comment by cliffckerr** [comment]
Not a Starsim bug but would be good to sort out! To do with parallel processing

**Comment by daniel-klein** [comment]
Not sure if related, but I have found the following line necessary in some situations on my Mac:
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

I don't have an exhaustive list of the "situations," might just be debugging from VSCode.

**Comment by devclinton** [comment]
Could a quick first pass of this bug just be documenting the workaround in our documentation until we can find a better way to address the issue?

**Comment by cliffckerr** [comment]
That would be nice, but it's hard to reproduce the bug and I haven't found a workaround on Windows yet ...

**Comment by cliffckerr** [comment]
Going to close, can reopen if it comes up again
