### ISSUE TITLE
Demographic results should be handled like other modules

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#497]
I'm writing a custom demographics module based on Pregnancy. A custom intervention averts pregnancy-related deaths. However, there's no way to record true results (after demographic and intervention updates). Most other modules `update_results` near the end of `sim.step`. It's not as easy as calling update results because demographic modules have customized `update_results`, these will need to conform.

**Comment by kaa2102** [comment]
This would be an good topic to discuss during a Starsim meeting. In seeking to align Births with Pregnancies/Deaths, I want to store data on who the mothers are and when they give birth. I was considering (1) creating a property sim.people.mother and sim.people.ti_mother or (2) using sim.results.

**Comment by cliffckerr** [comment]
Closed by #504
