### ISSUE TITLE
Consider website

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#499]
Currently, http://starsim.org just redirects to the GitHub org. Do we want a proper landing page like, say, https://pola.rs/?

**Comment by devclinton** [comment]
Could we just do this with gh pages?

**Comment by JSchripsema-IDM** [comment]
I'm currently working with ForumOne to build out a template for all of the tools pages on idmod.org so they can have more in-depth information and will have a landing page in place for Starsim by the Symposium.
