### ISSUE TITLE
StaticNet Initialize parameters not working

### ISSUE THREAD

**Issue by RHull-IDM** [starsimhub/starsim#513]
I can only get StaticNet to work by passing in a networkx graph. The code in the `initialize()` function suggests that we should be able to pass in the other pars and allow the graph to be generated automatically, but with the v0.5.0 changes to allowable pars, `n_contacts` and `p` are not permitted because they're not in the default pars list.

To recreate:

```
import starsim
starsim.StaticNet(n_contacts=100)
# also
starsim.StaticNet(p=0.01)
```

**Comment by cliffckerr** [comment]
Closed by #527
