### ISSUE TITLE
Refactor MaternalNet() add_pairs() method

### ISSUE THREAD

**Issue by kaa2102** [starsimhub/starsim#518]
PR # 514 will make change Births from deterministic to stochastic `ss.bernoulli(p=scaled_birth_rate)` and CRN-safe by linking new babies to mothers. network.py MaternalNet() has the add_pairs() method that adds connections between mothers and unborn babies. However, the logic is not connected downstream to link to newly created uids for babies [ happens via demographics.py & sim.people.grow() ].

https://github.com/starsimhub/starsim/pull/514
[Link to code in network.py (https://github.com/starsimhub/starsim/blob/fbd242d290c529797ad49d5c8fefbe478a7229e0/starsim/network.py#L802C1-L810C21
)
```
    def add_pairs(self, mother_inds=None, unborn_inds=None, dur=None):
        """ Add connections between pregnant women and their as-yet-unborn babies """
        if mother_inds is None:
            return 0
        else:
            n = len(mother_inds)
            beta = np.ones(n)
            self.append(p1=mother_inds, p2=unborn_inds, beta=beta, dur=dur)
            return n

```

**Comment by cliffckerr** [comment]
Done, I think?
