### ISSUE TITLE
Add native R interface and release on CRAN

### ISSUE THREAD

**Issue by roberthinch** [starsimhub/starsim#523]
Many epidemiology modellers use R instead of Python, so having Starsim easily available in R would help its uptake (especially if released in CRAN). Currently it can be accessed in R (as any Python package) using the R package reticulate, however, this take some effort and the code still looks very Python like (might scare of some R users). Adding a light R wrapper to make using Starsim in R more native would aid many R only users.  

The basic idea would be to use some simple R objects (i.e .R6) to mirror the Python objects, which would despatch all the calls to the underlying Python code. In a few circumstances it will be necessary to add a few extra lines of native R code (e.g. rendering of plots). Additionally we would add some simple utility functions in R so Starsim could be used by people who don't want to deal with the objects directly.

**Comment by devclinton** [comment]
I wonder if we can leverage reticulate for something like this?

**Comment by devclinton** [comment]
This could be an interesting expansion between 1.0 and 2.0 depending on the lift. I will start some basic research to see the effort needed for this, and then bring my findings back to this ticket

**Comment by cliffckerr** [comment]
Done: see https://r.starsim.org
