### ISSUE TITLE
Multisim.reduce() needs to be refactored to handle results objects

### ISSUE THREAD

**Issue by kaa2102** [starsimhub/starsim#538]
The `sim.results` object has changed so the foreach loops used in reduce() and called from mean(), and median() need to be refactored to iterate over multidimensions sim results, e.g., births, deaths, disease=sir, etc.

Also, the `quantiles` dictionary is missing or has been deleted.

**Comment by kaa2102** [comment]
PR #541 incorporates needed changes to Multisim.reduce() as they were needed to expand test coverage

**Comment by cliffckerr** [comment]
Closed by #541
