### ISSUE TITLE
Mixing pools

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#604]
We have several users asking for more generic network mixing, like the mixing pools in EMOD. This could prep-like mixing groups for TB (Deven request) or to recreate published work in RSV (Steve request). This feature would have been helpful for some COVID modeling applications as well. Hoping for efficiency gains along with greater ease of use.

**Comment by daniel-klein** [comment]
I started writing some code, but don't have time to move this forward quickly if others want to take the lead.

**Comment by cliffckerr** [comment]
Closed by #710
