### ISSUE TITLE
Consider building a simple HIV model

### ISSUE THREAD

**Issue by rnunez-IDM** [starsimhub/starsim#61]
We would like to understand how the sampling framework affects the patterns seen in phylogenetic trees for HIV epidemics.  A specific question to answer would be: Could sampling explain that genetic clustering patterns for HIV in Southern Africa countries are different than the ones seen in Europe and North America? One way of addressing this question is by using a model that supports, very broadly, the following items:
1. Multiple networks or key populations, for example, HET, FSW (Female Sexual Workers), and MSM (Men who have Sex with Men). 
2. Each of these subpopulations share some mixing patterns, demographics, and risk factors, independently. 
3. The networks interact among them (with some mixing patterns allowing this combination). For example, HET males pairing with individuals in FSW.
4. For initial exploratory analyses, we don’t need a very sophisticated HIV model. There are many details involved in HIV models that require great precision (many of those implemented in EMOD, for example). The models in this particular application, however, should support transmission/acquisition heterogeneity, as well as some parameters that allow to control risk factors and pairing characteristics per agent or individual.
5. We need testing interventions that puts some individuals under treatment (ART) and reduce their risk of transmitting/acquiring HIV.
6. Some individuals may be selected for testing and, if positive, the “sample” would be sequenced. The sampling time (or time after acquiring infection) should be a parameter.
7. Both testing and genetic sequencing interventions should implement stratified sampling, and the weights given to each strata should be input parameters.
8. The output of a model must include a linelist with all transmission events including, at least, information about the infector id, infected id, time of infection, time of testing, and the time that a test was selected for sequencing. This output will then be used to simulate a phylogenetic tree, and to estimate genetic clustering patterns. We should also be able to get information about the population (for example, to compute the average number of contacts per key population).
9. One or more summary statistics that characterize clustering patterns could be used as calibration targets. Then, custom cost/objective functions for calibration should be supported by the model.

**Comment by cliffckerr** [comment]
See https://github.com/starsimhub/stisim instead
