### ISSUE TITLE
Asymmetric configuration of demographic rates

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#621]
The rate parameters for Births (`birth_rate') and Deaths (`death_rate`) are applied to the whole population as a denominator whereas the seemingly-similar parameter (`fertility_rate`) for Pregnancy is only applied to women. This difference in denominators could lead to misconfiguration?

The difference in parameter names (`fertility_rate` vs `birth_rate`) is helpful and seemingly technically correct, but we still might need better documentation to be clear there's a factor of ~2 difference here!

Seems like this might primarily be a documentation issue, I've labeled as such.

This said, we could minimally improve the code comment regarding the `units` parameter for pregnancy. It's not wrong, but could be more clear to say "per 1000 women" for Pregnancy and "per 1000 people" for Births.
```python
units = 1e-3, # Assumes fertility rates are per 1000. If using percentages, switch this to 1
```

**Comment by cliffckerr** [comment]
Closed by #745
