### ISSUE TITLE
Tag Current Version Before Merging Redesign Branches into Main

### ISSUE THREAD

**Issue by menriquez-IDM** [starsimhub/starsim#649]
## *** reminder ***

Before merging the redesign branches into main, we should create a tag on the current version to maintain a stable reference point. This will help ensure a smooth transition and allow us to track progress during the Symposium.

## Priority:
High — to prepare for the Symposium.

**Comment by cliffckerr** [comment]
Good suggestion. Will do a `v1.0.2` release today and tag it.

**Comment by cliffckerr** [comment]
Done!
https://pypi.org/project/starsim/1.0.2/
