### ISSUE TITLE
Issue with numpy dependency?

### ISSUE THREAD

**Issue by jsheen** [starsimhub/starsim#678]
<img width="563" alt="Screenshot 2024-10-03 at 2 00 30 PM" src="https://github.com/user-attachments/assets/26c76e30-0910-4c3d-804c-ed954ee65aa7">

numpy version: 1.22.4
Python version: 3.9.7

I was able to do 'pip install starsim' with no errors.

**Comment by cliffckerr** [comment]
Hi @jsheen -- try `pip install numpy==1.24.4` and see if that fixes it? If so we will update the requirements to ensure this issue is resolved!

**Comment by jsheen** [comment]
I tried a few things (unfortuately at the same time) and it is now working!
- uninstalled and reinstalled anaconda-navigator
- updated numpy version 1.26.4
- updated conda to version 24.9.1
- updated python to version 3.12.4

**Comment by cliffckerr** [comment]
Glad it's working! I think the NumPy update was probably the most important, but possibly Python too.
