### ISSUE TITLE
Basic natural history - HIV

### ISSUE THREAD

**Issue by robynstuart** [starsimhub/starsim#7]
Write a basic natural history for HIV.

Lots of decisions to be made here re. what level of detail to include. At a minimum, the basic version will probably need CD4 and viral load. 

- [ ] Literature review of existing models
- [ ] #283
- [ ] Decide on which interventions to include
- [ ] Decide on preliminary data to calibrate to as validation
- [ ] Implement disease model structure
- [ ] Implement interventions
- [ ] Perform calibration/validation

**Comment by cliffckerr** [comment]
See https://github.com/starsimhub/stisim instead
