### ISSUE TITLE
Beta calculations

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#706]
Let's say dt=1/365 and I want beta=0.12 on each day (this for RSV). What would I choose for `v` in `pars['beta']=ss.beta(v)`?

Math from `time_prob`, after inversion, suggests:
```
v = 1 - np.exp(365*np.log(1 - 0.12))
```
BUT this returns 1.0, and that's clearly not right. 365-fold compounding is a bear!

if v=0.99, the resulting daily probability is just 0.0125, an order of magnitude too small!

**Comment by cliffckerr** [comment]
The short answer is that you should _never_ use `unit='year'` and `dt=1/365` -- use `unit='day'` and `dt=1` instead! I don't know if we want to make this throw an exception, but maybe we should :laughing: 

If you _really_ want to do this (no!!!!), you can specify `self_dt` for timepars, e.g. `ss.beta(0.12, unit='year', self_dt=1/365)`. But please don't do this!

**Comment by Komondi** [comment]
8u

**Comment by daniel-klein** [comment]
Thanks @cliffckerr, let me try changing the unit - that's a great suggestion. I don't think we can appropriately raise an exception, but we might be able to raise a warning / suggestion if dt is very small.
