### ISSUE TITLE
Demographics & Units

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#709]
- [x] Births and Deaths need to be time unit aware.
- [x] Rename "units", which is currently used to scale results e.g. 1/1000, considering units now has other meaning.

Rates should have units like ss.peryear, but if they don't and user does specify non-year units, we'll likely need to multiply by
```
time_factor = ss.time_ratio(unit1=self.unit, unit2='year')
```

**Comment by daniel-klein** [comment]
PR #710 uses this `time_factor` "hack" and does now appear to be compatible with units, but the framework would benefit from a more robust handling of units in demographics.

**Comment by daniel-klein** [comment]
I would like to suggest elevating the priority of this issue. Simulations on `rc2.1.0` are currently quite broken when the user wishes to use units other than `year`. Changing the default units for demographic modules to `year` is not a solution.

**Comment by daniel-klein** [comment]
While a refactor is warranted, even simple handling as we have done in other modules could work. For example in `Deaths`, the `death_rate` parameter could be an appropriate `TimePar`. We have the mechanics, just need to hook it up!

**Comment by cliffckerr** [comment]
Closing as remaining work is covered by #732
