### ISSUE TITLE
Starsim tries to attempt an invalid modulo operation

### ISSUE THREAD

**Issue by vgdeven** [starsimhub/starsim#722]
`  File "/Users/devengokhale/Documents/GitHub/starsim/starsim/sim.py", line 292, in start_step
    if not (self.ti % int(1.0 / self.verbose)):
            ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero`

**Comment by cliffckerr** [comment]
Closed by #710
