### ISSUE TITLE
time-varying time pars

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#793]
For parameters like beta, we'd love to be able to give the value `v` as a function to be called on each time step. So something like:

```python
beta = ss.beta(v=lambda sim: np.interp(sim.t.ti, [0, 25], [0.01, 0.02]))
```

With @vgdeven.

**Comment by cliffckerr** [comment]
I'm not sure how this would work since timepars don't store the sim. How would the argument to the lambda function be supplied?

I would suggest instead writing a custom `net_beta()` function for the network.

**Comment by cliffckerr** [comment]
Closing this, see #803 instead
