### ISSUE TITLE
MultiSim shrink size & limit

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#824]
MultiSim shrink has a default `size_limit` of 1.0 (MB) for each module.

Module size is calculated as
```python
sc.checkmem(mod, descend=0).bytesize[0]/1e6
```

However, it seems like this might not be working correctly with Sciris v3? Instead when I do
```python
sc.checkmem(mod, descend=True, subtotals=True).bytesize[0]/1e6
```
I get much more reasonable sizes, which are also much larger.

Please check the calculation and likely up the size_limit to more like 15 MB or more.

The impact is MANY warnings which could be distracting to users.

**Comment by cliffckerr** [comment]
@daniel-klein can you give an example? It seems to work for me:
```py
import sciris as sc
import starsim as ss

sim = ss.Sim(diseases='sis', networks='random')
sim.init()

msim = ss.MultiSim(base_sim=sim)
msim.run()

print(sc.checkmem(msim, descend=0)) # 21.008 MB
msim.shrink()
print(sc.checkmem(msim, descend=0)) # 167.587 KB 
```

**Comment by cliffckerr** [comment]
Closing for now, but can revisit if needed.
